version: "3.0"

services:
  plugins-server:
    container_name: grafana-plugins-server
    image: grafana-plugins-server:1.0.0
    restart: unless-stopped
    ports:
    - 3011:3011
    healthcheck:
      test: curl --fail http://localhost:3011/login || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_USERS_DEFAULT_THEME: light
      GF_PLUGIN_REPO: "http://grafana-plugins-server:3011/plugins"
      GF_INSTALL_PLUGINS: "michaeldmoore-multistat-panel"
    #volumes:
      #- ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      #- grafana-data:/var/lib/grafana
    depends_on:
      - plugins-server
